---
abstract: 'manage Amazon S3 policies for HTTP POST forms'
author:
  - 'Flavio Poletti <flavio [at] polettix [dot] it>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Amazon-S3-Policy
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::MakeMaker: 6.048000
  JSON: 2.0
  Test::More: 0
  perl: 5.008000
  version: 0
version: v0.1.6
